server:
  port: 8080

---

spring:
  profiles: default
  # jpa:
  #   # properties:
  #   #   hibernate:
  #   #     show_sql: true
  #   #     format_sql: true
  # datasource:
  #   url: jdbc:h2:mem:testdb
  #   driverClassName: org.h2.Driver
  #   username: sa
  #   password:
  #   initialization-mode: always
  # h2:
  #   console:
  #     enabled: true
  datasource:
    url: jdbc:mysql://localhost:3307/testdb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driverClassName: org.h2.Driver
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database: mysql
    show-sql : true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments : true

  # cloud:
  #   stream:
  #     kafka:
  #       binder:
  #         brokers: localhost:9092
  #       streams:
  #         binder:
  #           configuration:
  #             default:
  #               key:
  #                 serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  #               value:
  #                 serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  #     bindings:
  #       event-in:
  #         group: PartyManagement
  #         destination: partymanagement
  #         contentType: application/json
  #       event-out:
  #         destination: partymanagement
  #         contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug




# server:
#   port: 8081
# ---
# spring:
#   # datasource:
#   #   url:  jdbc:h2:~/test
#   #   driverClassName: org.h2.Driver
#   #   username: sa
#   #   password:
#   #   initialization-mode: always

#   # h2:
#   #   console:
#   #     enabled: true
#   datasource:
#     url: jdbc:mysql://localhost:3307/testdb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#     driverClassName: org.h2.Driver
#     username: root
#     password: root
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     database: mysql
#     show-sql : true
#     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#     properties:
#       hibernate:
#         show_sql: true
#         format_sql: true
#         use_sql_comments : true
# spring:
#   profiles: docker
#   cloud:
#     stream:
#       kafka:
#         binder:
#           brokers: my-kafka:9092
#         streams:
#           binder:
#             configuration:
#               default:
#                 key:
#                   serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#                 value:
#                   serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#       bindings:
#         event-in:
#           group: PartyManagement
#           destination: partymanagement
#           contentType: application/json
#         event-out:
#           destination: partymanagement
#           contentType: application/json


