server:
  port: 8084

---

spring:
  profiles: default
  datasource:
    url: jdbc:mysql://party-management-db.mysql.database.azure.com:3306/party_management_dev?serverTimezone=Asia/Seoul&validationQuery="select 1"
    username: mungta
    password: andxk12#$
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database: mysql
    show-sql : true
#    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments : true
  cloud:
   stream:
     kafka:
       binder:
         brokers: localhost:9092
       bindings:
         partyCreated-out:
           producer:
             configuration:
               key:
                 serializer: org.apache.kafka.common.serialization.StringSerializer
         partyStatusChanged-in-0:
           consumer:
             configuration:
               key:
                 deserializer: org.apache.kafka.common.serialization.StringDeserializer
         partyMemberAccept-in-0:
           consumer:
             configuration:
               key:
                 deserializer: org.apache.kafka.common.serialization.StringDeserializer
         partyMemberCanceled-in-0:
           consumer:
             configuration:
               key:
                 deserializer: org.apache.kafka.common.serialization.StringDeserializer
     bindings:
       partyRegistered-out:
         destination: party-registered
         contentType: application/json
       partyStatusChanged-in-0:
         destination: party-status-changed
       partyMemberAccept-in-0:
         destination: party-member-accept
       partyMemberCanceled-in-0:
         destination: party-member-canceled

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

api:
  url:
    user: http://localhost:8081/api/user



# server:
#   port: 8081
# ---
# spring:
#   # datasource:
#   #   url:  jdbc:h2:~/test
#   #   driverClassName: org.h2.Driver
#   #   username: sa
#   #   password:
#   #   initialization-mode: always

#   # h2:
#   #   console:
#   #     enabled: true
#   datasource:
#     url: jdbc:mysql://localhost:3307/testdb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#     driverClassName: org.h2.Driver
#     username: root
#     password: root
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     database: mysql
#     show-sql : true
#     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#     properties:
#       hibernate:
#         show_sql: true
#         format_sql: true
#         use_sql_comments : true
# spring:
#   profiles: docker
#   cloud:
#     stream:
#       kafka:
#         binder:
#           brokers: my-kafka:9092
#         streams:
#           binder:
#             configuration:
#               default:
#                 key:
#                   serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#                 value:
#                   serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#       bindings:
#         event-in:
#           group: PartyManagement
#           destination: partymanagement
#           contentType: application/json
#         event-out:
#           destination: partymanagement
#           contentType: application/json


